{%- if pillar.keystone.server is defined and pillar.keystone.server.get('enabled') %}
{%- from "keystone/map.jinja" import monitoring with context %}
{% raw %}
server:
  alert:
    KeystoneAPIDown:
      if: >-
        openstack_api_check_status{service=~"keystone.*"} == 0
      for: 2m
      labels:
        severity: down
        service: "{{ $labels.service }}"
      annotations:
        summary: "Endpoint check for '{{ $labels.service }}' is down"
        description: >-
            Endpoint check for '{{ $labels.service }}' is down for 2 minutes
    KeystoneAPIServiceDown:
      if: >-
        http_response_status{service=~"keystone.*"} == 0
      for: 2m
      labels:
        severity: down
        service: "{{ $labels.service }}"
      annotations:
        summary: "HTTP check for '{{ $labels.service }}' down"
        description: >-
            The HTTP check for '{{ $labels.service }}' is down on {{ $labels.host }} for 2 minutes.
    KeystoneErrorLogsTooHigh:
{%- endraw %}
      {%- set log_threshold = monitoring.error_log_rate|float %}
      if: >-
        sum(rate(log_messages{service="keystone",level=~"error|emergency|fatal"}[5m])) without (level) > {{ log_threshold }}
{%- raw %}
      labels:
        severity: warning
        service: "{{ $labels.service }}"
      annotations:
        summary: 'Too many errors in {{ $labels.service }} logs'
        description: 'The rate of errors in {{ $labels.service }} logs over the last 5 minutes is too high on node {{ $labels.host }} (current value={{ $value }}, threshold={%- endraw %}{{ log_threshold }}).'
    KeystoneFailedAuthsTooHigh:
      {%- set auth_threshold = monitoring.failed_auths.percentage %}
      {%- set rate_threshold = monitoring.failed_auths.all_auths_rate|float %}
      if: >-
        rate(authentications_total_failed[5m]) > rate(authentications_total_all[5m]) * {{ auth_threshold }} / 100 and rate(authentications_total_all[5m]) > {{ rate_threshold }}
{%- raw %}
      labels:
        severity: warning
        service: keystone
      annotations:
        summary: 'Too many failed authentications in Keystone'
        description: 'The rate of failed authentications in Keystone over the last 5 minutes is too high (current value={{ $value }}, threshold={%- endraw %}{{ auth_threshold }}).'
    KeystoneAPITooSlow:
      {%- set response_time_threshold = monitoring.http_response_time_p90|float %}
      if: >-
        max by(host) (openstack_keystone_http_response_times_upper_90{http_method=~"^(GET|POST)$",http_status="2xx"}) >= {{ response_time_threshold }}
{%- raw %}
      for: 2m
      labels:
        severity: warning
        service: keystone
      annotations:
        summary: 'Keystone API too slow'
        description: 'The 90th percentile of the Keystone API response times for GET and POST requests is too high on node {{ $labels.host }} (current value={{ $value }}s, threshold={%- endraw %}{{ response_time_threshold }}s).'

{%- endif %}
